"""
Django settings for iceBreaker project.

Generated by 'django-admin startproject' using Django 2.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '2ln4y-g96&_4*u0mx(0du98rvlfw2*1ent0$&6@78jw=oa0o@e'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

CRISPY_TEMPLATE_PACK = 'bootstrap3'
# Application definition

INSTALLED_APPS = [
    'startFundraiser',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'djcelery',
    'django_inlinecss',
    'widget_tweaks',
    'ckeditor',
    'ckeditor_uploader',
    'register',
    'social_django',
    'marketplace',
    'community',
    'polls',
    'testimony',
    'mathfilters',
    'crispy_forms',
    'captcha',
    'stripe',
]
AUTHENTICATION_BACKENDS=[
    'social_core.backends.github.GithubOAuth2',
    'social_core.backends.google.GoogleOAuth2',
    'django.contrib.auth.backends.ModelBackend',
    'register.authentication.EmailAuthBackend',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'ruthala.shiva512@gmail.com'
EMAIL_HOST_PASSWORD = 'Charan@01'
EMAIL_PORT = 587
EMAIL_USE_TLS = True


ROOT_URLCONF = 'iceBreaker.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',

            ],
        },
    },
]

WSGI_APPLICATION = 'iceBreaker.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
# STATICFILES_DIRS = [
#     os.path.join(BASE_DIR, "static"),
# ]
MEDIA_URL ='/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

CKEDITOR_JQUERY_URL = 'https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js'

CKEDITOR_UPLOAD_PATH = 'uploads/'
CKEDITOR_IMAGE_BACKEND = "pillow"

if DEBUG:
    # test keys
    STRIPE_PUBLISHABLE_KEY = 'pk_test_uv520wrOAmj5S0R6pSMqfQuO'
    STRIPE_SECRET_KEY = 'sk_test_9RtMPnED0F2g7hQJ3eOpvRBe'
    BT_ENVIRONMENT='sandbox'
    BT_MERCHANT_ID='dvz9yrrcm82f2wyw'
    BT_PUBLIC_KEY='mt4yjrfht47g24m6'
    BT_PRIVATE_KEY='84030d13637a181d7c5f198dabbca0c8'
else:
    # live keys
    STRIPE_PUBLISHABLE_KEY = 'YOUR STRIPE LIVE PUB KEY'
    STRIPE_SECRET_KEY = 'YOUR STRIPE LIVE SECRET KEY'


CKEDITOR_CONFIGS = {
    'default':{
        'toolbar': 'Custom',
        'height': 250,
        'width': 500,
        'toolbar_Custom':[
            ['Bold', 'Link', 'Image'],
        ],
    },
    'special':{
        'toolbar':'Special',
        'toolbar_Special':[
            ['Bold','CodeSnippet'],
        ],
        'extraPlugins': 'codesnippet',
    }
}

SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = '583325362406-eq68ddqmlcbbgc8efroq2gsqblf6aorc.apps.googleusercontent.com'
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = 'y3J9xxStLn48N4DC5ba9ihFF'

SOCIAL_AUTH_GITHUB_KEY = 'c4b98d42763ae00ed025'
SOCIAL_AUTH_GITHUB_SECRET = '54e3b9a046cd91b7bdda30936c9236a5f5b82b09'


RECAPTCHA_PUBLIC_KEY = '6Ldtk38UAAAAAAKvFYzqT7hsKCheERhhz_Dh4JuM'
RECAPTCHA_PRIVATE_KEY = '6Ldtk38UAAAAAG9_BTTra0vpBF8i4w9ET9JCRsMR'
NOCAPTCHA = True
