# Generated by Django 2.0.5 on 2018-11-18 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimony', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimony',
            name='commented',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
