# Generated by Django 2.0.6 on 2018-11-17 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='thumb',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='body',
            new_name='overview',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='title',
            new_name='product_title',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Domain',
            new_name='product_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
