# Generated by Django 2.0.6 on 2018-12-08 04:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_auto_20181207_1826'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transcation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('product_title', models.CharField(max_length=100)),
                ('product_type', models.CharField(max_length=100, null=True)),
                ('cost', models.FloatField(null=True)),
                ('token', models.CharField(max_length=20)),
                ('date_backed', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
