# Generated by Django 2.0.6 on 2018-12-08 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0009_transcation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcation',
            name='product_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='marketplace.product'),
        ),
    ]
