# Generated by Django 2.0.5 on 2018-12-01 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0009_cart_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cost',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
