# Generated by Django 2.0.5 on 2018-12-02 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0013_auto_20181202_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product',
            field=models.ManyToManyField(to='marketplace.product'),
        ),
    ]
