# Generated by Django 2.0.5 on 2018-12-08 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0016_auto_20181207_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='cost',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
