# Generated by Django 2.0.6 on 2018-12-10 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0019_transaction'),
        ('marketplace', '0010_auto_20181208_1017'),
    ]

    operations = [
    ]
