# Generated by Django 2.0.6 on 2018-12-10 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0020_merge_20181211_0034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transcation',
            name='product_title',
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='Transcation',
        ),
    ]
