# Generated by Django 2.1.1 on 2018-11-04 21:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20181105_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 11, 4, 21, 2, 54, 466571, tzinfo=utc), null=True),
        ),
    ]
