# Generated by Django 2.1.1 on 2018-11-08 19:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20181109_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 11, 8, 19, 58, 10, 517331, tzinfo=utc), null=True),
        ),
    ]
