# Generated by Django 2.1.1 on 2018-11-10 12:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_auto_20181109_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 11, 10, 12, 4, 28, 721155, tzinfo=utc), null=True),
        ),
    ]
