# Generated by Django 2.1.1 on 2018-11-11 06:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_auto_20181111_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 11, 11, 6, 39, 40, 635105, tzinfo=utc), null=True),
        ),
    ]
