# Generated by Django 2.0.5 on 2018-11-17 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0019_auto_20181117_2329'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(max_length=300)),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='answer',
        ),
    ]
