# Generated by Django 2.1.2 on 2018-11-30 11:08

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Backers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backer', models.CharField(max_length=50)),
                ('amount', models.FloatField()),
                ('date_backed', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_Title', models.CharField(max_length=200)),
                ('campaign_Tagline', models.CharField(max_length=200)),
                ('campaign_Card_Image', models.ImageField(blank=True, null=True, upload_to='')),
                ('campaign_Category', models.CharField(choices=[('creative', (('comics', 'comics'), ('art', 'art'))), ('tech', (('education', 'education'), ('phones', 'phones'))), ('community', (('environment', 'environment'), ('culture', 'culture')))], max_length=20)),
                ('country', models.CharField(default='India', max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media')),
                ('tags', models.CharField(blank=True, max_length=200, null=True)),
                ('overview', models.TextField(max_length=500)),
                ('story', models.TextField(blank=True, max_length=500, null=True)),
                ('goal', models.FloatField()),
                ('start_Date', models.DateField()),
                ('end_Date', models.DateField()),
                ('pledged', models.FloatField(default=0.0)),
                ('people_pledged', models.IntegerField(default=0)),
                ('campaign_Status', models.CharField(default='created', max_length=10)),
                ('likes', models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=1000)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('camp', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='startFundraiser.Campaign')),
            ],
        ),
        migrations.CreateModel(
            name='Faqs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, max_length=100)),
                ('answer', models.TextField(blank=True, max_length=200)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startFundraiser.Campaign')),
            ],
            options={
                'verbose_name_plural': 'FAQs',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('description2', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=1000)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('author', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('comment', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='startFundraiser.comment')),
            ],
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startFundraiser.Campaign')),
            ],
        ),
        migrations.AddField(
            model_name='backers',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startFundraiser.Campaign'),
        ),
    ]
