# Generated by Django 2.1.2 on 2018-11-30 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startFundraiser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='campaign_Status',
        ),
    ]
