# Generated by Django 2.1.2 on 2018-12-06 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startFundraiser', '0002_remove_campaign_campaign_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='video',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
