# Generated by Django 2.1.2 on 2018-12-06 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startFundraiser', '0003_campaign_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='campaign_status',
            field=models.CharField(choices=[('created', 'Campaign Created'), ('started', 'Campaign Started'), ('successfully', 'Campaign Ended Successfully'), ('unsuccessfully', 'Campaign Ended Unsuccesfully')], default='created', max_length=120),
        ),
    ]
