# Generated by Django 2.1.2 on 2018-12-06 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startFundraiser', '0004_campaign_campaign_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='campaign_Title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
