# Generated by Django 2.1.2 on 2018-12-07 09:35

from django.db import migrations, models
import startFundraiser.models


class Migration(migrations.Migration):

    dependencies = [
        ('startFundraiser', '0006_campaign_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='tags',
            field=models.CharField(blank=True, max_length=200, null=True, validators=[startFundraiser.models.validate_tags]),
        ),
    ]
