# Generated by Django 2.1.2 on 2018-12-07 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('startFundraiser', '0007_auto_20181207_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('perks', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startFundraiser.Campaign')),
            ],
        ),
    ]
