# Generated by Django 2.1.2 on 2018-12-07 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startFundraiser', '0009_campaign_perks'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='delivery',
            field=models.BooleanField(default=False),
        ),
    ]
