# Generated by Django 2.0.5 on 2018-12-11 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startFundraiser', '0012_auto_20181210_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='backers',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='backers',
            name='token',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
