# Generated by Django 2.0.5 on 2018-12-11 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startFundraiser', '0013_auto_20181211_1821'),
        ('startFundraiser', '0015_rewardclaimed'),
    ]

    operations = [
    ]
