# Generated by Django 2.0.5 on 2018-12-06 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_temp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temp',
            name='num',
        ),
    ]
