# Generated by Django 2.1.2 on 2018-11-03 21:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='member',
            new_name='MemberTable',
        ),
    ]
