# Generated by Django 2.1.2 on 2018-11-05 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_auto_20181103_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouptable',
            name='address',
            field=models.CharField(default='', max_length=100),
        ),
    ]
