# Generated by Django 2.1.2 on 2018-11-18 09:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_updatetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='updatetable',
            name='date',
            field=models.DateField(default=datetime.date(2018, 11, 18)),
        ),
    ]
