# Generated by Django 2.1.2 on 2018-11-18 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0007_updatetable_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='updatetable',
            name='date',
        ),
    ]
