# Generated by Django 2.0.5 on 2018-12-11 23:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0008_remove_updatetable_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouptable',
            name='date',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='grouptable',
            name='number',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='grouptable',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='grouptable',
            name='type',
            field=models.CharField(default='', max_length=100),
        ),
    ]
